# Use Bun
FROM oven/bun:1.3.8 AS reactapp

ARG APP_DIR=/opt/tigerpath
RUN mkdir "$APP_DIR"
RUN mkdir "$APP_DIR/frontend"

WORKDIR "$APP_DIR/frontend"

ADD frontend/package.json .
ADD frontend/bun.lock .

RUN bun install --frozen-lockfile --ignore-scripts

EXPOSE 3000

ADD frontend .
