# Use Python 3.6
FROM python:3.6

# Arguments
ARG APP_DIR=/opt/tigerpath

# Environment variables (dev only)
ENV SECRET_KEY=no7bxov1^uh=ksbp-xyw=#%4pn@01naitpdfj=-3*kao-3w93a
ENV DATABASE_URL postgres://username:password@localhost:port/name # change this
ENV ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
ENV DJANGO_SETTINGS_MODULE=config.settings.development
ENV PORT=8000
ENV PYTHONUNBUFFERED=1

# Create a new folder
RUN mkdir "$APP_DIR"

# Set working directory
WORKDIR "$APP_DIR"

# Install dependencies
ADD requirements.txt "$APP_DIR"
RUN pip install -r "$APP_DIR/requirements.txt"

# Expose port (not used in Heroku)
EXPOSE "$PORT"

# Add all the files
ADD . "$APP_DIR"

# Collect static files and apply migrations
RUN python manage.py collectstatic --noinput
RUN python manage.py migrate --noinput

# Start server
CMD python manage.py runserver 0.0.0.0:$PORT
