const BASE_THEME = {
  darkGreyText: '#181818',
  lightGrey: '#d9d9d9',
  darkGrey: '#767676',
  greySemBody: '#f5f5f5',
  greenSemBody: '#eaffb8',
  redSemBody: '#ffe9e4',
};

export const TIGERPATH_THEME_OPTIONS = {
  purple: {
    ...BASE_THEME,
    name: 'Purple',
    fallSemHeaderColor: '#b67be2',
    springSemHeaderColor: '#ddd6ff',
    ECHeaderColor: '#ec775f',
    courseText: '#5a23a4',
    courseFill: '#ddd6ff',
    courseBorder: '#c8bbff',
    searchFillStart: '#ead8ff',
    searchFillEnd: '#ded3ff',
    searchPillFill: 'rgba(188, 137, 237, 0.45)',
    searchText: '#5922a5',
    searchActionFill: '#ffffff',
    searchActionText: '#3f167a',
    searchActionBorder: '#b89de8',
    activePlanFill: '#ddd6ff',
    activePlanBorder: '#b99df7',
    requirementFillStart: '#dff6b4',
    requirementFillEnd: '#e1ff9a',
    requirementText: '#247427',
    panelTagDistFill: '#efe0ff',
    panelTagDistText: '#4a1f87',
    panelLinkFill: '#eee7ff',
    panelLinkText: '#3f167a',
    panelLinkBorder: '#cbbaf4',
    accent: '#4a1f87',
  },
  orange: {
    ...BASE_THEME,
    name: 'Orange',
    fallSemHeaderColor: '#ffad7a',
    springSemHeaderColor: '#ffe7d6',
    ECHeaderColor: '#ef6c45',
    courseText: '#a83312',
    courseFill: '#ffe6da',
    courseBorder: '#ffc9b0',
    searchFillStart: '#ffd1bd',
    searchFillEnd: '#ffe0d2',
    searchPillFill: 'rgba(255, 151, 104, 0.36)',
    searchText: '#a83312',
    searchActionFill: '#fffaf6',
    searchActionText: '#7e290d',
    searchActionBorder: '#ffad7a',
    activePlanFill: '#ffe6da',
    activePlanBorder: '#ffad7a',
    requirementFillStart: '#eaffb8',
    requirementFillEnd: '#e1ff9a',
    requirementText: '#3a6f1f',
    panelTagDistFill: '#ffe6da',
    panelTagDistText: '#8a2a0d',
    panelLinkFill: '#fff1e8',
    panelLinkText: '#7e290d',
    panelLinkBorder: '#ffbd96',
    accent: '#c64019',
  },
  blue: {
    ...BASE_THEME,
    name: 'Blue',
    fallSemHeaderColor: '#80d4de',
    springSemHeaderColor: '#dff7fb',
    ECHeaderColor: '#4cb7c3',
    courseText: '#0c8192',
    courseFill: '#dcf4f6',
    courseBorder: '#bee9ef',
    searchFillStart: '#c7eef5',
    searchFillEnd: '#dff6fb',
    searchPillFill: 'rgba(116, 205, 218, 0.34)',
    searchText: '#087789',
    searchActionFill: '#ffffff',
    searchActionText: '#075f6e',
    searchActionBorder: '#80d4de',
    activePlanFill: '#dcf4f6',
    activePlanBorder: '#80d4de',
    requirementFillStart: '#eaffb8',
    requirementFillEnd: '#e1ff9a',
    requirementText: '#247427',
    panelTagDistFill: '#ddf5f9',
    panelTagDistText: '#075f6e',
    panelLinkFill: '#e7f8fb',
    panelLinkText: '#075f6e',
    panelLinkBorder: '#9adce5',
    accent: '#006f80',
  },
  pink: {
    ...BASE_THEME,
    name: 'Pink',
    fallSemHeaderColor: '#ff9fc7',
    springSemHeaderColor: '#ffe4ef',
    ECHeaderColor: '#f46196',
    courseText: '#a80e4c',
    courseFill: '#ffe3ef',
    courseBorder: '#ffc1da',
    searchFillStart: '#ffd2e5',
    searchFillEnd: '#ffe2ef',
    searchPillFill: 'rgba(255, 135, 186, 0.35)',
    searchText: '#a80e4c',
    searchActionFill: '#ffffff',
    searchActionText: '#83093b',
    searchActionBorder: '#ff9fc7',
    activePlanFill: '#ffe3ef',
    activePlanBorder: '#ff9fc7',
    requirementFillStart: '#eaffb8',
    requirementFillEnd: '#e1ff9a',
    requirementText: '#247427',
    panelTagDistFill: '#ffe3ef',
    panelTagDistText: '#83093b',
    panelLinkFill: '#fff0f6',
    panelLinkText: '#83093b',
    panelLinkBorder: '#ffb3d2',
    accent: '#b70f55',
  },
};

export const DEFAULT_TIGERPATH_THEME = 'purple';

export function getTigerPathTheme(themeName) {
  const normalizedThemeName = themeName === 'sunset' ? 'orange' : themeName;
  return TIGERPATH_THEME_OPTIONS[normalizedThemeName] || TIGERPATH_THEME_OPTIONS[DEFAULT_TIGERPATH_THEME];
}

export function getTigerPathThemeVariables(themeName) {
  const theme = getTigerPathTheme(themeName);
  return {
    '--tp-course-text': theme.courseText,
    '--tp-course-fill': theme.courseFill,
    '--tp-course-border': theme.courseBorder,
    '--tp-search-fill-start': theme.searchFillStart,
    '--tp-search-fill-end': theme.searchFillEnd,
    '--tp-search-pill-fill': theme.searchPillFill,
    '--tp-search-text': theme.searchText,
    '--tp-search-action-fill': theme.searchActionFill,
    '--tp-search-action-text': theme.searchActionText,
    '--tp-search-action-border': theme.searchActionBorder,
    '--tp-active-plan-fill': theme.activePlanFill,
    '--tp-active-plan-border': theme.activePlanBorder,
    '--tp-requirement-fill-start': theme.requirementFillStart,
    '--tp-requirement-fill-end': theme.requirementFillEnd,
    '--tp-requirement-text': theme.requirementText,
    '--tp-panel-surface': '#ffffff',
    '--tp-panel-body': '#f0f1f3',
    '--tp-panel-border': '#d8d8d8',
    '--tp-panel-rule': '#eeeeee',
    '--tp-panel-overlay': 'rgba(18, 18, 18, 0.18)',
    '--tp-panel-overlay-mobile': 'rgba(18, 18, 18, 0.28)',
    '--tp-panel-shadow': 'rgba(0, 0, 0, 0.12)',
    '--tp-panel-card-shadow': 'rgba(0, 0, 0, 0.08)',
    '--tp-panel-scrollbar': '#bfc2c8',
    '--tp-panel-muted': '#5f5f5f',
    '--tp-panel-text': '#242424',
    '--tp-panel-close-hover': '#b3261e',
    '--tp-panel-rating-text': '#ffffff',
    '--tp-panel-tag-code-fill': '#ebebeb',
    '--tp-panel-tag-code-text': '#3f3f3f',
    '--tp-panel-tag-pdf-fill': '#fff2c5',
    '--tp-panel-tag-pdf-text': '#6c5100',
    '--tp-panel-tag-dist-fill': theme.panelTagDistFill,
    '--tp-panel-tag-dist-text': theme.panelTagDistText,
    '--tp-panel-link-fill': theme.panelLinkFill,
    '--tp-panel-link-text': theme.panelLinkText,
    '--tp-panel-link-border': theme.panelLinkBorder,
    '--tp-accent': theme.accent,
  };
}
