# All the university 3-letter department designations
DEPTS = {
    "AAS": "African American Studies",
    "AFS": "African Studies",
    "AMS": "American Studies",
    "ANT": "Anthropology",
    "AOS": "Atmospheric & Oceanic Sciences",
    "APC": "Appl and Computational Math",
    "ARA": "Arabic",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "ASA": "Asian American Studies",
    "AST": "Astrophysical Sciences",
    "ATL": "Atelier",
    "BCS": "Bosnian-Croatian-Serbian",
    "CBE": "Chemical and Biological Engr",
    "CEE": "Civil and Environmental Engr",
    "CGS": "Cognitive Science",
    "CHI": "Chinese",
    "CHM": "Chemistry",
    "CHV": "Center for Human Values",
    "CLA": "Classics",
    "CLG": "Classical Greek",
    "COM": "Comparative Literature",
    "COS": "Computer Science",
    "CTL": "Center for Teaching & Learning",
    "CWR": "Creative Writing",
    "CZE": "Czech",
    "DAN": "Dance",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "ECS": "European Cultural Studies",
    "EEB": "Ecology and Evol Biology",
    "EGR": "Engineering",
    "ELE": "Electrical Engineering",
    "ENE": "Energy Studies",
    "ENG": "English",
    "ENT": "Entrepreneurship",
    "ENV": "Environmental Studies",
    "EPS": "Contemporary European Politics",
    "FIN": "Finance",
    "FRE": "French",
    "FRS": "Freshman Seminars",
    "GEO": "Geosciences",
    "GER": "German",
    "GHP": "Global Health & Health Policy",
    "GLS": "Global Seminar",
    "GSS": "Gender and Sexuality Studies",
    "HEB": "Hebrew",
    "HIN": "Hindi",
    "HIS": "History",
    "HLS": "Hellenic Studies",
    "HOS": "History of Science",
    "HPD": "History/Practice of Diplomacy",
    "HUM": "Humanistic Studies",
    "ISC": "Integrated Science Curriculum",
    "ITA": "Italian",
    "JDS": "Judaic Studies",
    "JPN": "Japanese",
    "JRN": "Journalism",
    "KOR": "Korean",
    "LAO": "Latino Studies",
    "LAS": "Latin American Studies",
    "LAT": "Latin",
    "LCA": "Lewis Center for the Arts",
    "LIN": "Linguistics",
    "MAE": "Mech and Aerospace Engr",
    "MAT": "Mathematics",
    "MED": "Medieval Studies",
    "MOD": "Media and Modernity",
    "MOG": "Modern Greek",
    "MOL": "Molecular Biology",
    "MSE": "Materials Science and Engr",
    "MTD": "Music Theater",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "ORF": "Oper Res and Financial Engr",
    "PAW": "Ancient World",
    "PER": "Persian",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "PLS": "Polish",
    "POL": "Politics",
    "POP": "Population Studies",
    "POR": "Portuguese",
    "PSY": "Psychology",
    "QCB": "Quantitative Computational Bio",
    "REL": "Religion",
    "RES": "Russian, East Europ, Eurasian",
    "RUS": "Russian",
    "SAN": "Sanskrit",
    "SAS": "South Asian Studies",
    "SLA": "Slavic Languages and Lit",
    "SML": "Statistics & Machine Learning",
    "SOC": "Sociology",
    "SPA": "Spanish",
    "STC": "Science and Technology Council",
    "SWA": "Swahili",
    "THR": "Theater",
    "TPP": "Teacher Preparation",
    "TRA": "Translation, Intercultural Com",
    "TUR": "Turkish",
    "TWI": "Twi",
    "URB": "Urban Studies",
    "URD": "Urdu",
    "VIS": "Visual Arts",
    "WRI": "Princeton Writing Program",
    "WWS": "Woodrow Wilson School",
}

AB_DEPTS = {
    "AAS": "African American Studies",
    "ANT": "Anthropology",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "AST": "Astrophysical Sciences",
    "CHM": "Chemistry",
    "CLA": "Classics",
    "COM": "Comparative Literature",
    "COS": "Computer Science",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "EEB": "Ecology and Evol Biology",
    "ENG": "English",
    "FIT": "French and Italian",
    "GEO": "Geosciences",
    "GER": "German",
    "HIS": "History",
    "MAT": "Mathematics",
    "MOL": "Molecular Biology",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "POL": "Politics",
    "PSY": "Psychology",
    "REL": "Religion",
    "SLA": "Slavic Languages and Lit",
    "SOC": "Sociology",
    "SPO": "Spanish and Portuguese",
    "WWS": "Woodrow Wilson School",
}

AB_CONCENTRATIONS = {
    "AAS": "African American Studies",
    "ANT": "Anthropology",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "AST": "Astrophysical Sciences",
    "CHM": "Chemistry",
    "CLA": "Classics",
    "COM": "Comparative Literature",
    "COS-AB": "Computer Science - A.B.",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "EEB": "Ecology and Evolutionary Biology",
    "ENG": "English",
    "FIT": "French and Italian",
    "GEO": "Geosciences",
    "GER": "German",
    "HIS": "History",
    "MAT": "Mathematics",
    "MOL": "Molecular Biology",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "POL": "Politics",
    "PSY": "Psychology",
    "REL": "Religion",
    "SLA": "Slavic Languages and Literatures",
    "SOC": "Sociology",
    "SPO": "Spanish and Portuguese",
    "WWS": "Woodrow Wilson School of Public and International Affairs",
}

BSE_CONCENTRATIONS = {
    "CBE": "Chemical and Biological Engineering",
    "CEE": "Civil and Environmental Engineering",
    "COS-BSE": "Computer Science - B.S.E.",
    "ELE": "Electrical Engineering",
    "MAE": "Mechanical and Aerospace Engineering",
    "ORF": "Operations Research and Financial Engineering",
}

CERTIFICATES = [
    "African American Studies",
    "African Studies",
    "American Studies",
    "Applications of Computing",
    "Applied and Computational Mathematics",
    "Archaeology",
    "Architecture and Engineering",
    "Biophysics",
    "Cognitive Science",
    "Contemporary European Politics and Society",
    "Creative Writing",
    "Dance",
    "East Asian Studies",
    "Engineering and Management Systems",
    "Engineering Biology",
    "Engineering Physics",
    "Entrepreneurship",
    "Environmental Studies",
    "Ethnographic Studies",
    "European Cultural Studies",
    "Finance",
    "Gender and Sexuality Studies",
    "Geological Engineering",
    "Global Health and Health Policy",
    "Hellenic Studies",
    "History and the Practice of Diplomacy",
    "Humanistic Studies",
    "Jazz Studies",
    "Judaic Studies",
    "Language and Culture",
    "Latin American Studies",
    "Latino Studies",
    "Linguistics",
    "Materials Science and Engineering",
    "Medieval Studies",
    "Music Theater",
    "Musical Performance",
    "Near Eastern Studies",
    "Neuroscience",
    "Planets and Life",
    "Quantitative and Computational Biology",
    "Robotics and Intelligent Systems",
    "Russian, East European, and Eurasian Studies",
    "South Asian Studies",
    "Statistics and Machine Learning",
    "Sustainable Energy",
    "Teacher Preparation",
    "Technology and Society",
    "Theater",
    "Translation and Intercultural Communication",
    "Urban Studies",
    "Values and Public Life",
    "Visual Arts",
]

# language departments
LANG_DEPTS = {
    "ARA": "Arabic",
    "BCS": "Bosnian-Croatian-Serbian", # TODO: confirm
    #"???": "Bulgarian" # TODO: confirm
    "SLA": "Slavic Languages and Lit", # TODO: confirm
    "CHI": "Chinese",
    "CZE": "Czech",
    "FRE": "French",
    "GER": "German",
    "MOG": "Modern Greek",
    "CLG": "Classical Greek",
    "HEB": "Hebrew",
    "HIN": "Hindi",
    "ITA": "Italian",
    "JPN": "Japanese",
    "KOR": "Korean",
    "LAT": "Latin",
    "PER": "Persian",
    "PLS": "Polish", # TODO: confirm
    "POR": "Portuguese", # TODO: confirm
    "RUS": "Russian",
    "SPA": "Spanish",
    "SWA": "Swahili",
    "TUR": "Turkish",
    "TWI": "Twi", # TODO: confirm
    "URD": "Urdu",
} # unsure if some of these can count for AB foreign language requirement. TODO: confirm
