# All the university 3-letter department designations
DEPTS = {
    "AAS": "African American Studies",
    "AFS": "African Studies",
    "AMS": "American Studies",
    "ANT": "Anthropology",
    "AOS": "Atmospheric & Oceanic Sciences",
    "APC": "Appl and Computational Math",
    "ARA": "Arabic",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "ASA": "Asian American Studies",
    "AST": "Astrophysical Sciences",
    "ATL": "Atelier",
    "BCS": "Bosnian-Croatian-Serbian",
    "CBE": "Chemical and Biological Engr",
    "CEE": "Civil and Environmental Engr",
    "CGS": "Cognitive Science",
    "CHI": "Chinese",
    "CHM": "Chemistry",
    "CHV": "Center for Human Values",
    "CLA": "Classics",
    "CLG": "Classical Greek",
    "COM": "Comparative Literature",
    "COS": "Computer Science",
    "CTL": "Center for Teaching & Learning",
    "CWR": "Creative Writing",
    "CZE": "Czech",
    "DAN": "Dance",
    "EAS": "East Asian Studies",
    "ECE": "Electrical and Computer Engineering",
    "ECO": "Economics",
    "ECS": "European Cultural Studies",
    "EEB": "Ecology and Evol Biology",
    "EGR": "Engineering",
    "ELE": "Electrical Engineering",
    "ENE": "Energy Studies",
    "ENG": "English",
    "ENT": "Entrepreneurship",
    "ENV": "Environmental Studies",
    "EPS": "Contemporary European Politics",
    "FIN": "Finance",
    "FRE": "French",
    "FRS": "Freshman Seminars",
    "GEO": "Geosciences",
    "GER": "German",
    "GHP": "Global Health & Health Policy",
    "GLS": "Global Seminar",
    "GSS": "Gender and Sexuality Studies",
    "HEB": "Hebrew",
    "HIN": "Hindi",
    "HIS": "History",
    "HLS": "Hellenic Studies",
    "HOS": "History of Science",
    "HPD": "History/Practice of Diplomacy",
    "HUM": "Humanistic Studies",
    "ISC": "Integrated Science Curriculum",
    "ITA": "Italian",
    "JDS": "Judaic Studies",
    "JPN": "Japanese",
    "JRN": "Journalism",
    "KOR": "Korean",
    "LAO": "Latino Studies",
    "LAS": "Latin American Studies",
    "LAT": "Latin",
    "LCA": "Lewis Center for the Arts",
    "LIN": "Linguistics",
    "MAE": "Mech and Aerospace Engr",
    "MAT": "Mathematics",
    "MED": "Medieval Studies",
    "MOD": "Media and Modernity",
    "MOG": "Modern Greek",
    "MOL": "Molecular Biology",
    "MPP": "Music Performance",
    "MSE": "Materials Science and Engr",
    "MTD": "Music Theater",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "ORF": "Oper Res and Financial Engr",
    "PAW": "Ancient World",
    "PER": "Persian",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "PLS": "Polish",
    "POL": "Politics",
    "POP": "Population Studies",
    "POR": "Portuguese",
    "PSY": "Psychology",
    "QCB": "Quantitative Computational Bio",
    "REL": "Religion",
    "RES": "Russian, East Europ, Eurasian",
    "RUS": "Russian",
    "SAN": "Sanskrit",
    "SAS": "South Asian Studies",
    "SLA": "Slavic Languages and Lit",
    "SML": "Statistics & Machine Learning",
    "SOC": "Sociology",
    "SPA": "Spanish",
    "SPI": "Public and International Affairs",
    "STC": "Science and Technology Council",
    "SWA": "Swahili",
    "THR": "Theater",
    "TPP": "Teacher Preparation",
    "TRA": "Translation, Intercultural Com",
    "TUR": "Turkish",
    "TWI": "Twi",
    "URB": "Urban Studies",
    "URD": "Urdu",
    "VIS": "Visual Arts",
    "WRI": "Princeton Writing Program",
    "WWS": "Public and International Affairs",
}

AB_DEPTS = {
    "AAS": "African American Studies",
    "ANT": "Anthropology",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "AST": "Astrophysical Sciences",
    "CHM": "Chemistry",
    "CLA": "Classics",
    "COM": "Comparative Literature",
    "COS": "Computer Science",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "EEB": "Ecology and Evol Biology",
    "ENG": "English",
    "FIT": "French and Italian",
    "GEO": "Geosciences",
    "GER": "German",
    "HIS": "History",
    "MAT": "Mathematics",
    "MOL": "Molecular Biology",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "POL": "Politics",
    "PSY": "Psychology",
    "REL": "Religion",
    "SLA": "Slavic Languages and Lit",
    "SOC": "Sociology",
    "SPI": "Public and International Affairs",
    "SPO": "Spanish and Portuguese",
}

AB_CONCENTRATIONS = {
    "AAS": "African American Studies",
    "ANT": "Anthropology",
    "ARC": "Architecture",
    "ART": "Art and Archaeology",
    "AST": "Astrophysical Sciences",
    "CHM": "Chemistry",
    "CLA": "Classics",
    "COM": "Comparative Literature",
    "COS-AB": "Computer Science - A.B.",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "EEB": "Ecology and Evolutionary Biology",
    "ENG": "English",
    "FIT": "French and Italian",
    "GEO": "Geosciences",
    "GER": "German",
    "HIS": "History",
    "MAT": "Mathematics",
    "MOL": "Molecular Biology",
    "MUS": "Music",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "PHI": "Philosophy",
    "PHY": "Physics",
    "POL": "Politics",
    "POR": "Portuguese",
    "PSY": "Psychology",
    "REL": "Religion",
    "SLA": "Slavic Languages and Literatures",
    "SOC": "Sociology",
    "SPA": "Spanish",
    "SPI": "Public and International Affairs",
    "SPO": "Spanish and Portuguese",
}

BSE_CONCENTRATIONS = {
    "CBE": "Chemical and Biological Engineering",
    "CEE": "Civil and Environmental Engineering",
    "COS-BSE": "Computer Science - B.S.E.",
    "ECE": "Electrical and Computer Engineering",
    "MAE": "Mechanical and Aerospace Engineering",
    "ORF": "Operations Research and Financial Engineering",
}

CERTIFICATES = {
    "AAS": "African American Studies",
    "ACE": "Architecture and Engineering",
    "ACM": "Applied and Computational Mathematics",
    "AFS": "African Studies",
    "AMS": "American Studies",
    "ASA": "Asian American Studies",
    "AST": "Planets and Life",
    "PAC": "Applications of Computing",
    "ART": "Archaeology",
    "CHI": "Chinese Language",
    "CWR": "Creative Writing",
    "DAN": "Dance",
    "EAS": "East Asian Studies",
    "EMS": "Engineering and Management Systems",
    "ENT": "Entrepreneurship",
    "ENV": "Environmental Studies",
    "FIN": "Finance",
    "GER": "German Language and Culture",
    "GEO": "Geological Engineering",
    "GHP": "Global Health and Health Policy",
    "GSS": "Gender and Sexuality Studies",
    "HLS": "Hellenic Studies",
    "HOS": "History of Science, Technology and Medicine",
    "HPD": "History and the Practice of Diplomacy",
    "HUM": "Humanistic Studies",
    "JPN": "Japanese Language",
    "KOR": "Korean Language",
    "LAC-CLA": "Language and Culture: Classics",
    "LAC-EAS": "Language and Culture: East Asian Studies",
    "LAC-POR": "Portuguese Language and Culture",
    "LAC-SPA": "Language and Culture: Spanish",
    "LAS": "Latin American Studies",
    "LAO": "Latino Studies",
    "LIN": "Linguistics",
    "MED": "Medieval Studies",
    "MPP": "Music Performance",
    "MSE": "Materials Science and Engineering",
    "NES": "Near Eastern Studies",
    "NEU": "Neuroscience",
    "OQDS": "Optimization and Quantitative Decision Science",
    "PEB": "Engineering Biology",
    "QCB": "Quantitative and Computational Biology",
    "RIS": "Robotics and Intelligent Systems",
    "SAS": "South Asian Studies",
    "SML": "Statistics and Machine Learning",
    "TAS-E": "Technology and Society - Energy Track",
    "TAS-IT": "Technology and Society - IT Track",
    "THR": "Theater",
    "TPP": "Teacher Preparation",
    "TRA": "Translation and Intercultural Communication",
    "URB": "Urban Studies",
    "VIS": "Visual Arts",
    "VPL": "Values and Public Life",
}

# language departments
LANG_DEPTS = {
    "ARA": "Arabic",
    "BCS": "Bosnian-Croatian-Serbian",  # TODO: confirm
    # "???": "Bulgarian" # TODO: confirm
    "SLA": "Slavic Languages and Lit",  # TODO: confirm
    "CHI": "Chinese",
    "CZE": "Czech",
    "FRE": "French",
    "GER": "German",
    "MOG": "Modern Greek",
    "CLG": "Classical Greek",
    "HEB": "Hebrew",
    "HIN": "Hindi",
    "ITA": "Italian",
    "JPN": "Japanese",
    "KOR": "Korean",
    "LAT": "Latin",
    "PER": "Persian",
    "PLS": "Polish",  # TODO: confirm
    "POR": "Portuguese",  # TODO: confirm
    "RUS": "Russian",
    "SAN": "Sanskrit",
    "SPA": "Spanish",
    "SWA": "Swahili",
    "TUR": "Turkish",
    "TWI": "Twi",  # TODO: confirm
    "URD": "Urdu",
}  # unsure if some of these can count for AB foreign language requirement. TODO: confirm
