# Generated by Django 2.0.4 on 2018-04-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.TextField()),
                ("rating", models.FloatField(default=0)),
                ("description", models.TextField()),
                ("registrar_id", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Course_Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dept", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=10)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_listing_set",
                        to="tigerpath.Course",
                    ),
                ),
            ],
            options={
                "ordering": ["dept", "number"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.CharField(max_length=20)),
                ("end_time", models.CharField(max_length=20)),
                ("days", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("isDefault", models.BooleanField(default=False)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("CLA", "class"),
                            ("DRI", "drill"),
                            ("EAR", "ear training"),
                            ("FIL", "film"),
                            ("LAB", "lab"),
                            ("LEC", "lecture"),
                            ("PRE", "precept"),
                            ("SEM", "seminar"),
                            ("STU", "studio"),
                        ],
                        max_length=3,
                    ),
                ),
                ("section_enrollment", models.IntegerField(default=0)),
                ("section_capacity", models.IntegerField(default=999)),
                ("section_registrar_id", models.CharField(default="", max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="tigerpath.Course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "term_code",
                    models.CharField(db_index=True, default=1184, max_length=4, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetings",
                to="tigerpath.Section",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(to="tigerpath.Professor"),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tigerpath.Semester"
            ),
        ),
    ]
