# Generated by Django 2.0.4 on 2018-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerpath', '0002_major_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
