# Generated by Django 2.0.4 on 2018-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0003_userprofile_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="major",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="year",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
