# Generated by Django 2.0.4 on 2018-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0005_userprofile_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
