# Generated by Django 2.0.3 on 2018-04-24 23:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0006_auto_20180422_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_schedule",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
