# Generated by Django 2.0.3 on 2018-04-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0008_course_dist_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semesters",
            field=models.TextField(default=""),
        ),
    ]
