# Generated by Django 2.0.3 on 2018-04-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0009_course_semesters"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
    ]
