# Generated by Django 2.0.3 on 2018-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerpath', '0011_auto_20180426_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cross_listings',
            field=models.TextField(default=''),
        ),
    ]
