# Generated by Django 2.0.3 on 2018-04-27 04:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0012_course_cross_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="all_semesters",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=4), blank=True, default=list, size=None
            ),
        ),
    ]
