# Generated by Django 2.0.4 on 2018-05-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tigerpath", "0016_auto_20180511_0105"),
    ]

    operations = [
        migrations.AddField(
            model_name="major",
            name="supported",
            field=models.BooleanField(default=False),
        ),
    ]
