# Generated by Django 4.2.16 on 2026-02-12 02:30

from django.db import migrations, models
import tigerpath.models


class Migration(migrations.Migration):

    dependencies = [
        ("tigerpath", "0018_alter_semester_term_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="term_code",
            field=models.CharField(
                db_index=True,
                default=tigerpath.models.get_default_term_code,
                max_length=4,
                unique=True,
            ),
        ),
    ]
