# Generated by Django 4.2.28 on 2026-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerpath', '0020_scheduleplan_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
