# Generated by Django 4.2.28 on 2026-04-02 20:59

from django.db import migrations, models
import django.db.models.deletion


def backfill_plan_major(apps, schema_editor):
    SchedulePlan = apps.get_model('tigerpath', 'SchedulePlan')
    for plan in SchedulePlan.objects.select_related('user_profile', 'major').all():
        if plan.major_id is None and plan.user_profile and plan.user_profile.major_id:
            plan.major_id = plan.user_profile.major_id
            plan.save(update_fields=['major'])


class Migration(migrations.Migration):

    dependencies = [
        ('tigerpath', '0021_alter_scheduleplan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tigerpath.major'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='minors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_plan_major, migrations.RunPython.noop),
    ]
